import React from 'react'
import Header from './Elements/Header'
import Footer from './Elements/Footer'

export default function Terms() {
  return (
    <div>
      {/* START LOADER */}
      <div id="loader-wrapper">
        <div id="loading-center-absolute">
          <div className="object" id="object_four" />
          <div className="object" id="object_three" />
          <div className="object" id="object_two" />
          <div className="object" id="object_one" />
        </div>
        <div className="loader-section section-left" />
        <div className="loader-section section-right" />
      </div>
      {/* END LOADER */}
      {/* START HEADER */}

      {/* END HEADER */}{/* START SECTION BANNER */}
      <section className="section_breadcrumb bg_navy_blue" data-z-index={1} data-parallax="scroll" data-image-src="assets/images/home_banner_bg.png">
        <Header />
        <div className="container">
          <div className="row">
            <div className="col-lg-12 col-md-12 col-sm-12">
              <div className="banner_text text-center">
                <h1 className="animation animated fadeInUp" data-animation="fadeInUp" data-animation-delay="1.1s" style={{ animationDelay: '1.1s', opacity: 1 }}>Term Of Service</h1>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section>
        <div className="container">
          <div className="row">
            <div className="col-lg-12">
              <div className="title_border">
                <p>Disclaimer</p>

                <p>The information available through www.cryptossky.com is for your general information and use and is not intended to address your particular requirements. This information show on the site does not constitute any form of advice or recommendation by Cryptossky.com and is not intended to be relied upon by users in making (or refraining from making) any investment decisions. Appropriate independent advice should be obtained before making any such decision. Any arrangement made between you and any third party named in the site is at your sole risk and responsibility.</p>

                <p>For your information we would like to draw your attention to the following investment warnings:</p>

                <p>The price of plans and investments and the income derived from them can go down as well as up, and investors may not get back the amount they invested. The spread between the bid and offer prices of securities can be significant in volatile market conditions, especially for smaller companies. Realisation of small investments may be relatively costly. Past performance is not necessarily a guide to future performance. Where the information consists of pricing or performance data, the data contained therein has been obtained from company reports, financial reporting services, periodicals, and other sources believed reliable. The www.cryptossky.com site operates a policy of independence in relation to matters where the operator may have a material interest or conflict of interest. On conflict of interest such interest may arise from the receipt of advertising income, commissions based on business introduced payment for enhanced publication presence, holding of positions etc. Contributors employed or contracted by the company to provide site material are required to disregard any material interest or conflict of interest when giving advice through the site.</p>

                <p>Journalistic comment included on this site content is made to the best of the knowledge and belief of the writer, but no responsibility is accepted for actions based on such comment. www.cryptossky.com Terms of Service</p>

                <p>1. Definition of Investment.</p>

                <p>1.1 An investment is a limited amount of money that is made available to third parties, a company or a set of shares, in order to increase with the profits generated by a specific business project.</p>

                <p>1.2. All deposits must be made in the USDT cryptocurrency, at the address indicated on the New Deposit page of the website, hereinafter “Website”.</p>

                <p>1.3. Users of the website must know the limitations of their country regarding investments in cryptocurrencies and comply with current regulations on taxes.</p>

                <p>1.3.1. The official currency of the website is the dollar (USDT);</p>

                <p>1.3.2. The first payment will be sent on the first Saturday of the week following the date of the deposit. This amount will always be the same throughout the duration of the plan. We recommend making deposits on any day, but especially on Friday, Saturday and Sunday if you want to receive your first week's payment the following Saturday.</p>

                <p>1.3.3. Payments will be made directly to the USDT (Tron network) address offered by the investor and can be changed in their profile.</p>

                <p>1.3.4. The investor may have up to 2 accounts, one being personal and the other in the name of a legal entity. Withdrawals must be made separately and cannot be transferred from a personal account to another business account and vice versa. If the investor controls one or more accounts of family members, he must notify the administration offering the IDs of the users and there may not be more than six accounts in total.</p>

                <p>1.3.5. At the end of the active period of each plan, withdrawals made from the Basic plan will be charged with 10%. Standard plans are loaded with 5%. The Gold and Diamond Premium plan will be 3% and 1.5% respectively.</p>

                <p>1.3.6. Weekly payments will be executed in the early hours of Saturday. Withdrawals of the invested capital (end of the plan period) will be sent to the user between 6 to 72 hours later.</p>

                <p>1.3.7 Urgent withdrawals, made by our administration staff, will be charged an extra 3%. These withdrawals can only be made from Monday to Friday and are for immediate payment. The minimum amount allowed in urgent withdrawal requests cannot be less than 500 USDT. To request it, simply go to the “New Deposit” section and click on “Urgent Withdrawal”. An email message will be sent to the administration with the available balance and your USDT wallet.</p>

                <p>1.3.8 Deposits of the Basic and Standard plans can be withdrawn after 30 days with a 10% charge. Premium plans can be withdrawn after the first 60 days with a charge for the Gold and Diamond Plan of 15%. From the second month, 0.12% will be calculated each month, which will be applied extra in case of withdrawal before the expected completion time.</p>

                <p>Security of Access and Communications</p>

                <p>1.4. Users must, within a maximum period of 90 days, use the Google Authenticator app. After this time weekly withdrawals will be automatically blocked until this security system is activated. Unlocking is also automatic.</p>

                <p>1.5. Two ways have been provided to ensure access to your account by sending six digits. You can indicate if you wish, receive it by email, by phone in a text message or both at the same time. This option can be activated in your profile with a simple click.</p>

                <p>1.6. The website will have an internal news channel where any matter related to maintenance plans will be announced and must be announced at least 3 business days in advance. In the event of an unexpected technical incident, we will inform you immediately through our internal channel. A public and monthly digital newspaper will also be available that can be downloaded from the HOME page, giving an account of our business plans, especially the map of the way forward in the next 24 months.</p>

                <p>2. Bonuses, Draws and Referrals</p>

                <p>2.1. The investor will receive a 5% commission for each person who enters the website through his link and will obtain the same percentage in each renewal of his plan. This is limited to a direct total of 25 people.</p>

                <p>2.1.1. Referral commissions will be received in your wallet between the 1st and 5th of each month, provided that the following rule is met: If the investor has a basic plan, it must be 500 USDT. If you have a Standard plan it should be 2500. Premium plans meet the requirement by default.</p>

                <p>2.2. These 25 people can refer 25 new investors each, earning 2.5% of their second and last level.</p>

                <p>23. The total number of authorized referrals is 625 people per user.</p>

                <p>2.4. Users with at least one plan have the right to purchase tickets for apartment draws at the price of 25 USDT and up to a maximum of 25 tickets per user. These real estate properties will be available in Turkey and the United Arab Emirates.</p>

                <p>3. Investment limitation assets and functionality of the web</p>

                <p>3.1. For security reasons the number of investors may be limited. This limitation can occur at different times of the year. These limitations will affect the registration of new investors. There will be a waiting list where the new investor can register with their name, email and probable amount to invest.</p>

                <p>3.2. The waiting lists do not have priority for signing up first, but these are approved and accepted by the administration, according to the interests of the website.</p>

                <p>3.3. The system may limit the functionality of your account if any sign of intentionality is detected that may affect the website or the safety of investors. In case you use the right mouse button while inside the website, in order to access "inspect element" or use CTRL + Shift + C, your account will be instantly blocked. You will not be able to access until the administration contacts you, which could be within seven business days.</p>

                <p>4. definitive cancellation of the investment account</p>

                <p>4.1. The investor may cancel his account free of charge before ten business days have elapsed and only payments made up to that date may be deducted. After ten business days you will have a 10% penalty. Cancelled accounts lose the right to validate any previously purchased ticket for draws that the website has in progress, and therefore without the right to a refund. You must maintain at least one active plan so that, if you win a prize, you can claim it.</p>

                <p>4.2. Expiring plans can be renewed immediately, with three days to reactivate. The amount of the plan is automatically transferred to the wallet at the end of its activity period.</p>

                <p>5. Commissions for services</p>

                <p>5.1. Withdrawals from the basic plans at the end of the period have a charge of 10%, the Standard plans have a charge of 5% and the two PREMIUM plans, GOLD AND DIAMOND, have a charge of 3 and 1.5%, respectively.</p>

                <p>5.2. Withdrawals of interest obtained have a 1.5% commission charge.</p>

                <p>5.3. Urgent withdrawals have the charge that corresponds to your plan plus an extra charge of 3%. Urgent withdrawals must have a balance greater than 500 USDT available.</p>

                <p>5.4. 10% will be deducted from each deposit made for the GPF (Global Protection Funds) This percentage does not modify the amount of the active plan since the investor will see the total amount deposited in his account.</p>

                <p>6. Administration of Funds Received</p>

                <p>6.1. 80% of the funds obtained are used to expand the resources that guarantee weekly payments to investors. These resources are distributed in three major investment phases: the requests for concession of new gold lands in Uganda, Republic of Mali, Ghana and Nigeria, with a percentage of 20% (See the road map) The purchase and sale of properties in Dubai with a percentage of 45% and triangular arbitrage in the process of development of three different robots, with 15% of the total funds.</p>

                <p>6.2. The remaining 20% is used for the maintenance of dedicated servers, administration staff expenses, marketing, maintenance and presentations in different countries.</p>

                <p>6.3. Each of the categories of investment plans is responsible for weekly payments to investors in its category. In this way and according to the percentages established in section 6.1 of this document, the funds obtained by the Basic Plan and by the Standard Plans are invested to pay the payments of the investors of these plans.</p>

                <p>6. 4. With the Premium plans, the investment strategy is carried out directly on the purchase-sale of real estate properties in the United Arab Emirates.</p>

              </div>
            </div>
          </div>
        </div>
      </section>

      <a href="#" className="scrollup btn-default" style={{ display: 'none' }}><i className="ion-ios-arrow-up" /></a>
      <div className="spop-container spop--bottom-left" id="spop--bottom-left" />
      <Footer />
    </div>
  )
}
